#pragma once

#include <pybind11/pybind11.h>
#include <radiolib/protocols/PhysicalLayer/PhysicalLayer.h>

namespace py = pybind11;

using ModemType = ModemType_t;
using RadioModeType = RadioModeType_t;

using LoRaRate = LoRaRate_t;
using FSKRate = FSKRate_t;
using LrFhssRate = LrFhssRate_t;

using LoRaPacketConfig = LoRaPacketConfig_t;
using FSKPacketConfig = FSKPacketConfig_t;
using LrFhssPacketConfig = LrFhssPacketConfig_t;

using CADScanConfig = CADScanConfig_t;
using RSSIScanConfig = RSSIScanConfig_t;

using StandbyConfig = StandbyConfig_t;
using ReceiveConfig = ReceiveConfig_t;
using TransmitConfig = TransmitConfig_t;
using ChannelScanConfig = ChannelScanConfig_t;
using SleepConfig = SleepConfig_t;


enum ModuleStatus : std::int16_t {
	Normal = RADIOLIB_ERR_NONE,
	Unknown = RADIOLIB_ERR_UNKNOWN,
	ChipNotFound = RADIOLIB_ERR_CHIP_NOT_FOUND,
	MemoryAllocationFailed = RADIOLIB_ERR_MEMORY_ALLOCATION_FAILED,
	PacketTooLong = RADIOLIB_ERR_PACKET_TOO_LONG,
	TxTimeout = RADIOLIB_ERR_TX_TIMEOUT,
	RxTimeout = RADIOLIB_ERR_RX_TIMEOUT,
	CrcMismatch = RADIOLIB_ERR_CRC_MISMATCH,
	InvalidBandwidth = RADIOLIB_ERR_INVALID_BANDWIDTH,
	InvalidSpreadingFactor = RADIOLIB_ERR_INVALID_SPREADING_FACTOR,
	InvalidCodingRate = RADIOLIB_ERR_INVALID_CODING_RATE,
	InvalidBitRange = RADIOLIB_ERR_INVALID_BIT_RANGE,
	InvalidFrequency = RADIOLIB_ERR_INVALID_FREQUENCY,
	InvalidOutputPower = RADIOLIB_ERR_INVALID_OUTPUT_POWER,
	PreambleDetected = RADIOLIB_PREAMBLE_DETECTED,
	ChannelFree = RADIOLIB_CHANNEL_FREE,
	SpiWriteFailed = RADIOLIB_ERR_SPI_WRITE_FAILED,
	InvalidCurrentLimit = RADIOLIB_ERR_INVALID_CURRENT_LIMIT,
	InvalidPreambleLength = RADIOLIB_ERR_INVALID_PREAMBLE_LENGTH,
	InvalidGain = RADIOLIB_ERR_INVALID_GAIN,
	WrongModem = RADIOLIB_ERR_WRONG_MODEM,
	InvalidNumSamples = RADIOLIB_ERR_INVALID_NUM_SAMPLES,
	InvalidRssiOffset = RADIOLIB_ERR_INVALID_RSSI_OFFSET,
	InvalidEncoding = RADIOLIB_ERR_INVALID_ENCODING,
	LoraHeaderDamaged = RADIOLIB_ERR_LORA_HEADER_DAMAGED,
	Unsupported = RADIOLIB_ERR_UNSUPPORTED,
	InvalidDioPin = RADIOLIB_ERR_INVALID_DIO_PIN,
	InvalidRssiThreshold = RADIOLIB_ERR_INVALID_RSSI_THRESHOLD,
	NullPointer = RADIOLIB_ERR_NULL_POINTER,
	InvalidIrq = RADIOLIB_ERR_INVALID_IRQ,
	PacketTooShort = RADIOLIB_ERR_PACKET_TOO_SHORT,
	InvalidBitRate = RADIOLIB_ERR_INVALID_BIT_RATE,
	InvalidFrequencyDeviation = RADIOLIB_ERR_INVALID_FREQUENCY_DEVIATION,
	InvalidBitRateBwRatio = RADIOLIB_ERR_INVALID_BIT_RATE_BW_RATIO,
	InvalidRxBandwidth = RADIOLIB_ERR_INVALID_RX_BANDWIDTH,
	InvalidSyncWord = RADIOLIB_ERR_INVALID_SYNC_WORD,
	InvalidDataShaping = RADIOLIB_ERR_INVALID_DATA_SHAPING,
	InvalidModulation = RADIOLIB_ERR_INVALID_MODULATION,
	InvalidOokRssiPeakType = RADIOLIB_ERR_INVALID_OOK_RSSI_PEAK_TYPE,
	InvalidBitRateToleranceValue = RADIOLIB_ERR_INVALID_BIT_RATE_TOLERANCE_VALUE,
	InvalidSymbol = RADIOLIB_ERR_INVALID_SYMBOL,
	InvalidMicETelemetry = RADIOLIB_ERR_INVALID_MIC_E_TELEMETRY,
	InvalidMicETelemetryLength = RADIOLIB_ERR_INVALID_MIC_E_TELEMETRY_LENGTH,
	MicETelemetryStatus = RADIOLIB_ERR_MIC_E_TELEMETRY_STATUS,
	InvalidSsdvMode = RADIOLIB_ERR_INVALID_SSDV_MODE,
	InvalidImageSize = RADIOLIB_ERR_INVALID_IMAGE_SIZE,
	InvalidImageQuality = RADIOLIB_ERR_INVALID_IMAGE_QUALITY,
	InvalidSubsampling = RADIOLIB_ERR_INVALID_SUBSAMPLING,
	InvalidRttyShift = RADIOLIB_ERR_INVALID_RTTY_SHIFT,
	UnsupportedEncoding = RADIOLIB_ERR_UNSUPPORTED_ENCODING,
	InvalidDataRate = RADIOLIB_ERR_INVALID_DATA_RATE,
	InvalidAddressWidth = RADIOLIB_ERR_INVALID_ADDRESS_WIDTH,
	InvalidPipeNumber = RADIOLIB_ERR_INVALID_PIPE_NUMBER,
	AckNotReceived = RADIOLIB_ERR_ACK_NOT_RECEIVED,
	InvalidNumBroadAddrs = RADIOLIB_ERR_INVALID_NUM_BROAD_ADDRS,
	InvalidCrcConfiguration = RADIOLIB_ERR_INVALID_CRC_CONFIGURATION,
	LoraDetected = RADIOLIB_LORA_DETECTED,
	InvalidTcxoVoltage = RADIOLIB_ERR_INVALID_TCXO_VOLTAGE,
	InvalidModulationParameters = RADIOLIB_ERR_INVALID_MODULATION_PARAMETERS,
	SpiCmdTimeout = RADIOLIB_ERR_SPI_CMD_TIMEOUT,
	SpiCmdInvalid = RADIOLIB_ERR_SPI_CMD_INVALID,
	SpiCmdFailed = RADIOLIB_ERR_SPI_CMD_FAILED,
	InvalidSleepPeriod = RADIOLIB_ERR_INVALID_SLEEP_PERIOD,
	InvalidRxPeriod = RADIOLIB_ERR_INVALID_RX_PERIOD,
	InvalidCallsign = RADIOLIB_ERR_INVALID_CALLSIGN,
	InvalidNumRepeaters = RADIOLIB_ERR_INVALID_NUM_REPEATERS,
	InvalidRepeaterCallsign = RADIOLIB_ERR_INVALID_REPEATER_CALLSIGN,
	RangingTimeout = RADIOLIB_ERR_RANGING_TIMEOUT,
	InvalidPayload = RADIOLIB_ERR_INVALID_PAYLOAD,
	AddressNotFound = RADIOLIB_ERR_ADDRESS_NOT_FOUND,
	InvalidFunction = RADIOLIB_ERR_INVALID_FUNCTION,
	NetworkNotJoined = RADIOLIB_ERR_NETWORK_NOT_JOINED,
	DownlinkMalformed = RADIOLIB_ERR_DOWNLINK_MALFORMED,
	InvalidRevision = RADIOLIB_ERR_INVALID_REVISION,
	InvalidPort = RADIOLIB_ERR_INVALID_PORT,
	NoRxWindow = RADIOLIB_ERR_NO_RX_WINDOW,
	NoChannelAvailable = RADIOLIB_ERR_NO_CHANNEL_AVAILABLE,
	InvalidCid = RADIOLIB_ERR_INVALID_CID,
	UplinkUnavailable = RADIOLIB_ERR_UPLINK_UNAVAILABLE,
	CommandQueueFull = RADIOLIB_ERR_COMMAND_QUEUE_FULL,
	CommandQueueItemNotFound = RADIOLIB_ERR_COMMAND_QUEUE_ITEM_NOT_FOUND,
	ErrJoinNonceInvalid = RADIOLIB_ERR_JOIN_NONCE_INVALID,
	ErrMicMismatch = RADIOLIB_ERR_MIC_MISMATCH,
	ErrMulticastFcntInvalid = RADIOLIB_ERR_MULTICAST_FCNT_INVALID,
	ErrDwellTimeExceeded = RADIOLIB_ERR_DWELL_TIME_EXCEEDED,
	ErrChecksumMismatch = RADIOLIB_ERR_CHECKSUM_MISMATCH,
	ErrNoJoinAccept = RADIOLIB_ERR_NO_JOIN_ACCEPT,
	LorawanSessionRestored = RADIOLIB_LORAWAN_SESSION_RESTORED,
	LorawanNewSession = RADIOLIB_LORAWAN_NEW_SESSION,
	NoncesDiscarded = RADIOLIB_ERR_NONCES_DISCARDED,
	SessionDiscarded = RADIOLIB_ERR_SESSION_DISCARDED,
	InvalidMode = RADIOLIB_ERR_INVALID_MODE,
	InvalidWifiType = RADIOLIB_ERR_INVALID_WIFI_TYPE,
	GnssSubframeNotAvailable = RADIOLIB_ERR_GNSS_SUBFRAME_NOT_AVAILABLE,
};

void bind_types(py::module& module);

