#include "bind_types.h"

#include <pybind11/native_enum.h>

void bind_sx126x_types(py::module& module) {
	py::native_enum<Sx126xCommands>(module, "Sx126xCommands", "enum.IntEnum")
	    // operational modes commands
	    .value("Nop", Nop)
	    .value("SetSleep", SetSleep)
	    .value("SetStandby", SetStandby)
	    .value("SetFs", SetFs)
	    .value("SetTx", SetTx)
	    .value("SetRx", SetRx)
	    .value("StopTimerOnPreamble", StopTimerOnPreamble)
	    .value("SetRxDutyCycle", SetRxDutyCycle)
	    .value("SetCad", SetCad)
	    .value("SetTxContinuousWave", SetTxContinuousWave)
	    .value("SetTxInfinitePreamble", SetTxInfinitePreamble)
	    .value("SetRegulatorMode", SetRegulatorMode)
	    .value("Calibrate", Calibrate)
	    .value("CalibrateImage", CalibrateImage)
	    .value("SetPaConfig", SetPaConfig)
	    .value("SetRxTxFallbackMode", SetRxTxFallbackMode)
	    // operational modes commands
	    .value("WriteRegister", WriteRegister)
	    .value("ReadRegister", ReadRegister)
	    .value("WriteBuffer", WriteBuffer)
	    .value("ReadBuffer", ReadBuffer)
	    // DIO and IRQ control
	    .value("SetDioIrqParams", SetDioIrqParams)
	    .value("GetIrqStatus", GetIrqStatus)
	    .value("ClearIrqStatus", ClearIrqStatus)
	    .value("SetDio2AsRfSwitchCtrl", SetDio2AsRfSwitchCtrl)
	    .value("SetDio3AsTcxoCtrl", SetDio3AsTcxoCtrl)
	    // RF, modulation and packet commands
	    .value("SetRfFrequency", SetRfFrequency)
	    .value("SetPacketType", SetPacketType)
	    .value("GetPacketType", GetPacketType)
	    .value("SetTxParams", SetTxParams)
	    .value("SetModulationParams", SetModulationParams)
	    .value("SetPacketParams", SetPacketParams)
	    .value("SetCadParams", SetCadParams)
	    .value("SetBufferBaseAddress", SetBufferBaseAddress)
	    .value("SetLoraSymbNumTimeout", SetLoraSymbNumTimeout)
	    // status commands
	    .value("GetStatus", GetStatus)
	    .value("GetRssiInst", GetRssiInst)
	    .value("GetRxBufferStatus", GetRxBufferStatus)
	    .value("GetPacketStatus", GetPacketStatus)
	    .value("GetDeviceErrors", GetDeviceErrors)
	    .value("ClearDeviceErrors", ClearDeviceErrors)
	    .value("GetStats", GetStats)
	    .value("ResetStats", ResetStats)
	    .value("PramUpdate", PramUpdate)
	    .value("SetLbtScanParams", SetLbtScanParams)
	    .value("SetSpectrScanParams", SetSpectrScanParams)
	    .export_values()
	    .finalize();

	py::native_enum<Sx126xRegisters>(module, "Sx126xRegisters", "enum.IntEnum")
	    .value("RxGainRetention0", RxGainRetention0)
	    .value("RxGainRetention1", RxGainRetention1)
	    .value("RxGainRetention2", RxGainRetention2)
	    .value("VersionString", VersionString)
	    .value("HoppingEnable", HoppingEnable)
	    .value("LrFhssPacketLength", LrFhssPacketLength)
	    .value("LrFhssNumHoppingBlocks", LrFhssNumHoppingBlocks)
	    .value("LrFhssNumSymbolsFreqxMsb", LrFhssNumSymbolsFreqxMsb)
	    .value("LrFhssNumSymbolsFreqxLsb", LrFhssNumSymbolsFreqxLsb)
	    .value("LrFhssFreqx0", LrFhssFreqx0)
	    .value("LrFhssFreqx1", LrFhssFreqx1)
	    .value("LrFhssFreqx2", LrFhssFreqx2)
	    .value("LrFhssFreqx3", LrFhssFreqx3)
	    .value("SpectralScanResult", SpectralScanResult)
	    .value("DioxOutEnable", DioxOutEnable)
	    .value("DioxDriveStrength", DioxDriveStrength)
	    .value("DioxInEnable", DioxInEnable)
	    .value("DioxPullUpCtrl", DioxPullUpCtrl)
	    .value("DioxPullDownCtrl", DioxPullDownCtrl)
	    .value("TxBitbangEnable0", TxBitbangEnable0)
	    .value("PatchUpdateEnable", PatchUpdateEnable)
	    .value("TxBitbangEnable1", TxBitbangEnable1)
	    .value("WhiteningInitialMsb", WhiteningInitialMsb)
	    .value("WhiteningInitialLsb", WhiteningInitialLsb)
	    .value("RxTxPldLen", RxTxPldLen)
	    .value("CrcInitialMsb", CrcInitialMsb)
	    .value("CrcInitialLsb", CrcInitialLsb)
	    .value("CrcPolynomialMsb", CrcPolynomialMsb)
	    .value("CrcPolynomialLsb", CrcPolynomialLsb)
	    .value("SyncWord0", SyncWord0)
	    .value("SyncWord1", SyncWord1)
	    .value("SyncWord2", SyncWord2)
	    .value("SyncWord3", SyncWord3)
	    .value("SyncWord4", SyncWord4)
	    .value("SyncWord5", SyncWord5)
	    .value("SyncWord6", SyncWord6)
	    .value("SyncWord7", SyncWord7)
	    .value("NodeAddress", NodeAddress)
	    .value("BroadcastAddress", BroadcastAddress)
	    .value("PayloadLength", PayloadLength)
	    .value("PacketParams", PacketParams)
	    .value("LoraSyncTimeout", LoraSyncTimeout)
	    .value("IqConfig", IqConfig)
	    .value("LoraSyncWordMsb", LoraSyncWordMsb)
	    .value("LoraSyncWordLsb", LoraSyncWordLsb)
	    .value("Lora_RX_CODING_RATE", Lora_RX_CODING_RATE)
	    .value("FreqErrorRxCrc", FreqErrorRxCrc)
	    .value("SpectralScanStatus", SpectralScanStatus)
	    .value("RxAddrPtr", RxAddrPtr)
	    .value("RandomNumber0", RandomNumber0)
	    .value("RandomNumber1", RandomNumber1)
	    .value("RandomNumber2", RandomNumber2)
	    .value("RandomNumber3", RandomNumber3)
	    .value("SensitivityConfig", SensitivityConfig)
	    .value("RfFrequency0", RfFrequency0)
	    .value("RfFrequency1", RfFrequency1)
	    .value("RfFrequency2", RfFrequency2)
	    .value("RfFrequency3", RfFrequency3)
	    .value("RssiAvgWindow", RssiAvgWindow)
	    .value("RxGain", RxGain)
	    .value("TxClampConfig", TxClampConfig)
	    .value("AnaLna", AnaLna)
	    .value("LnaCapTuneN", LnaCapTuneN)
	    .value("LnaCapTuneP", LnaCapTuneP)
	    .value("AnaMixer", AnaMixer)
	    .value("OcpConfiguration", OcpConfiguration)
	    .value("RtcCtrl", RtcCtrl)
	    .value("XtaTrim", XtaTrim)
	    .value("XtbTrim", XtbTrim)
	    .value("Dio3OutVoltageCtrl", Dio3OutVoltageCtrl)
	    .value("EventMask", EventMask)
	    .value("PatchMemoryBase", PatchMemoryBase)
	    .export_values()
	    .finalize();
}
