#include "bind_physical_layer.h"

void bind_physical_layer(py::module& module) {
	py::class_<PhysicalLayer, PyPhysicalLayer, std::shared_ptr<PhysicalLayer>>(module, "PhysicalLayer")
	    .def(py::init<>())
	    .def("transmit", py::overload_cast<char const*, std::uint8_t>(&PhysicalLayer::transmit))
	    .def("transmit", py::overload_cast<std::uint8_t const*, size_t, std::uint8_t>(&PhysicalLayer::transmit))
	    .def("sleep", &PhysicalLayer::sleep)
	    .def("standby", py::overload_cast<>(&PhysicalLayer::standby))
	    .def("standby", py::overload_cast<std::uint8_t>(&PhysicalLayer::standby))
	    .def("startReceive", py::overload_cast<>(&PhysicalLayer::startReceive))
	    // .def("startReceive", py::overload_cast<std::uint32_t, >(&PhysicalLayer::startReceive))
	    .def("receive", &PhysicalLayer::receive)
	    .def("startTransmit", py::overload_cast<char const*, std::uint8_t>(&PhysicalLayer::startTransmit))
	    .def("startTransmit", py::overload_cast<std::uint8_t const*, size_t, std::uint8_t>(&PhysicalLayer::startTransmit))
	    .def("finishTransmit", &PhysicalLayer::finishTransmit)
	    .def("finishReceive", &PhysicalLayer::finishReceive)
	    .def("readData", &PhysicalLayer::readData)
	    .def("transmitDirect", &PhysicalLayer::transmitDirect)
	    .def("receiveDirect", &PhysicalLayer::receiveDirect)
	    .def("setFrequency", &PhysicalLayer::setFrequency)
	    .def("setBitRate", &PhysicalLayer::setBitRate)
	    .def("setFrequencyDeviation", &PhysicalLayer::setFrequencyDeviation)
	    .def("setDataShaping", &PhysicalLayer::setDataShaping)
	    .def("setEncoding", &PhysicalLayer::setEncoding)
	    .def("invertIQ", &PhysicalLayer::invertIQ)
	    .def("setOutputPower", &PhysicalLayer::setOutputPower)
	    .def("checkOutputPower", &PhysicalLayer::checkOutputPower)
	    .def("setSyncWord", &PhysicalLayer::setSyncWord)
	    .def("setPreambleLength", &PhysicalLayer::setPreambleLength)
	    // .def("setDataRate", &PhysicalLayer::setDataRate)
	    // .def("checkDataRate", &PhysicalLayer::checkDataRate)
	    .def("getPacketLength", &PhysicalLayer::getPacketLength)
	    .def("getRSSI", &PhysicalLayer::getRSSI)
	    .def("getSNR", &PhysicalLayer::getSNR)
	    // .def("calculateTimeOnAir", &PhysicalLayer::calculateTimeOnAir)
	    .def("getTimeOnAir", &PhysicalLayer::getTimeOnAir)
	    .def("calculateRxTimeout", &PhysicalLayer::calculateRxTimeout)
	    .def("getIrqMapped", &PhysicalLayer::getIrqMapped)
	    // .def("checkIrq", &PhysicalLayer::checkIrq)
	    .def("setIrq", &PhysicalLayer::setIrq)
	    .def("clearIrq", &PhysicalLayer::clearIrq)
	    .def("getIrqFlags", &PhysicalLayer::getIrqFlags)
	    .def("setIrqFlags", &PhysicalLayer::setIrqFlags)
	    .def("clearIrqFlags", &PhysicalLayer::clearIrqFlags)
	    .def("startChannelScan", py::overload_cast<>(&PhysicalLayer::startChannelScan))
	    // .def("startChannelScan", py::overload_cast<>(&PhysicalLayer::startChannelScan))
	    .def("getChannelScanResult", &PhysicalLayer::getChannelScanResult)
	    .def("scanChannel", py::overload_cast<>(&PhysicalLayer::scanChannel))
	    // .def("scanChannel", py::overload_cast<>(&PhysicalLayer::scanChannel))
	    .def("random", py::overload_cast<std::int32_t>(&PhysicalLayer::random))
	    .def("random", py::overload_cast<std::int32_t, std::int32_t>(&PhysicalLayer::random))
	    .def("randomByte", &PhysicalLayer::randomByte)
	    .def("startDirect", &PhysicalLayer::startDirect)
	    .def("setDirectSyncWord", &PhysicalLayer::setDirectSyncWord)
	    .def("setDirectAction", &PhysicalLayer::setDirectAction)
	    .def("readBit", &PhysicalLayer::readBit)
	    .def("available", &PhysicalLayer::available)
	    .def("dropSync", &PhysicalLayer::dropSync)
	    .def("read", &PhysicalLayer::read)
	    .def("setDIOMapping", &PhysicalLayer::setDIOMapping)
	    .def("setPacketReceivedAction", &PhysicalLayer::setPacketReceivedAction)
	    .def("clearPacketReceivedAction", &PhysicalLayer::clearPacketReceivedAction)
	    .def("setPacketSentAction", &PhysicalLayer::setPacketSentAction)
	    .def("clearPacketSentAction", &PhysicalLayer::clearPacketSentAction)
	    .def("setChannelScanAction", &PhysicalLayer::setChannelScanAction)
	    .def("clearChannelScanAction", &PhysicalLayer::clearChannelScanAction)
	    .def("setModem", &PhysicalLayer::setModem)
	    .def("getModem", &PhysicalLayer::getModem)
	    // .def("stageMode", &PhysicalLayer::stageMode)
	    .def("launchMode", &PhysicalLayer::launchMode)
	;
}
